# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseParemsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('param_key', models.CharField(max_length=50)),
                ('param_value', models.CharField(max_length=50)),
                ('simple_desc', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'CaseParemsInfo',
                'verbose_name': '\u7528\u4f8b\u53c2\u6570',
            },
        ),
        migrations.CreateModel(
            name='RequestMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('method_name', models.CharField(max_length=50)),
                ('method_desc', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'RequestMethod',
                'verbose_name': '\u8bf7\u6c42\u65b9\u5f0f',
            },
        ),
        migrations.CreateModel(
            name='RequestUrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('request_name', models.CharField(max_length=50)),
                ('request_url', models.CharField(max_length=50)),
                ('simple_desc', models.CharField(max_length=100, null=True)),
                ('other_desc', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('request_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.RequestMethod')),
            ],
            options={
                'db_table': 'RequestUrlInfo',
                'verbose_name': '\u8bf7\u6c42\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('belong_project', models.CharField(max_length=50)),
                ('include', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=20)),
                ('request', models.TextField()),
                ('active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('belong_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.RequestUrlInfo')),
            ],
            options={
                'db_table': 'TestCaseInfo',
                'verbose_name': '\u7528\u4f8b\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='caseparemsinfo',
            name='belong_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.TestCaseInfo'),
        ),
    ]
