# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseparemsinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='caseparemsinfo',
            name='param_key',
            field=models.CharField(max_length=50, verbose_name='\u8bf7\u6c42key'),
        ),
        migrations.AlterField(
            model_name='caseparemsinfo',
            name='param_value',
            field=models.CharField(max_length=50, verbose_name='\u8bf7\u6c42value'),
        ),
        migrations.AlterField(
            model_name='caseparemsinfo',
            name='simple_desc',
            field=models.CharField(max_length=100, null=True, verbose_name='\u7b80\u8981\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='caseparemsinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='requestmethod',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='requestmethod',
            name='method_desc',
            field=models.CharField(max_length=100, null=True, verbose_name='\u8bf7\u6c42\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='requestmethod',
            name='method_name',
            field=models.CharField(max_length=50, verbose_name='\u8bf7\u6c42\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='requestmethod',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='requesturlinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='requesturlinfo',
            name='request_name',
            field=models.CharField(max_length=50, verbose_name='\u8bf7\u6c42\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='requesturlinfo',
            name='request_url',
            field=models.CharField(max_length=50, verbose_name='\u8bf7\u6c42\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='requesturlinfo',
            name='simple_desc',
            field=models.CharField(max_length=100, null=True, verbose_name='\u8bf7\u6c42\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='requesturlinfo',
            name='status',
            field=models.IntegerField(default=1, verbose_name='\u8bf7\u6c42\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='requesturlinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='active',
            field=models.IntegerField(default=1, verbose_name='\u7528\u4f8b\u662f\u5426\u6267\u884c'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='belong_project',
            field=models.CharField(max_length=50, verbose_name='\u7528\u4f8b\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u7528\u4f8b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='status',
            field=models.IntegerField(default=1, verbose_name='\u7528\u4f8b\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='type',
            field=models.IntegerField(default=1, verbose_name='\u7528\u4f8b\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='testcaseinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
