# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20180324_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseparemsinfo',
            options={'verbose_name': 'CaseParemsInfo'},
        ),
        migrations.AlterModelOptions(
            name='requestmethod',
            options={'verbose_name': 'RequestMethod'},
        ),
        migrations.AlterModelOptions(
            name='requesturlinfo',
            options={'verbose_name': 'RequestUrlInfo'},
        ),
        migrations.AlterModelOptions(
            name='testcaseinfo',
            options={'verbose_name': 'TestCaseInfo'},
        ),
    ]
