# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20180324_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcaseinfo',
            name='include',
        ),
        migrations.RemoveField(
            model_name='testcaseinfo',
            name='request',
        ),
    ]
